#!/bin/sh -e
# shellcheck disable=2034,2091,3010,3037,3060 shell=busybox
# Custom UCI defaults script for Linksys MX4200/4300/5300 etc
# Create folder "files/etc/uci-defaults/" in build root and copy this script there.
# Customize to your needs.

# Uncomment the following line to capture all output to a log file
exec > /root/uci-defaults.log 2>&1

# Wireless radio0 specific settings
uci set wireless.radio0.htmode='HE1600'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.country='CN'

# Wireless radio1 specific settings
uci set wireless.radio1.htmode='HE40'
uci set wireless.radio1.channel='auto'
uci set wireless.radio1.country='CN'
